### ISSUE TITLE
Support Minor Versions

### ISSUE THREAD

**Issue by chopmann** [BRCDcomm/pynos#1]
Summary:
When using NOS version 6.0.2 the pynos library wont work.

Steps to reproduce:
Upgrade/Downgrade a VDX 6740 to Verion 6.0.2
Follow http://lkhill.com/brocade-pynos-python-libraries/ --> First Example.

Expected result:
dev.firmware_version
'6.0.2'

Error:
I dont have the error log. I since upgraded to 7.0.0
The following line is where (i guess) the error occurs:
https://github.com/BRCDcomm/pynos/blob/master/pynos/device.py#L158

Version 6.0.2 is not in the dictionary --> The Object ( Device(...) ) initialization wont work.

**Comment by LindsayHill** [comment]
I hit the same problem recently. The code needs updating around https://github.com/BRCDcomm/pynos/blob/master/pynos/device.py#L57, to add a new section for 6.0.2.

There's a patch going through internal review & testing now. Hopefully gets published soon.

**Comment by samirsss** [comment]
I've reviewed the code. Let me know if you want me to push the code once you've merged it Lindsay

**Comment by LindsayHill** [comment]
This change has been merged, and is now in pypi https://github.com/BRCDcomm/pynos/commit/fb659bb91d3ab79f5c48290ccb770c22b171eb23
