### ISSUE TITLE
Configuring Fabric-Virtual-Gateway and  global VE interface

### ISSUE THREAD

**Issue by chopmann** [BRCDcomm/pynos#2]
Is it possible to configure  Fabric-Virtual-Gateway and  global VE interface using pynos?

And if so, can you please post an example implementation for the "example configuration" down below?
http://www.brocade.com/content/html/en/configuration-guide/nos-601-l3guide/GUID-C17776F9-390E-4D06-A1A6-F02B998E7C3B.html

**Comment by chopmann** [comment]
Greping the source I found:
https://github.com/BRCDcomm/pynos/blob/7f8f0cb495c8da29c7567e7d01f96b095d9b6fb0/pynos/versions/ver_7/ver_7_0_0/yang/brocade_common_def.py#L1110

``` python
    def router_fabric_virtual_gateway_address_family_ipv4_enable_global(self, **kwargs):
        """Auto Generated Code
        """
        config = ET.Element("config")
        router = ET.SubElement(config, "router", xmlns="urn:brocade.com:mgmt:brocade-common-def")
        fabric_virtual_gateway = ET.SubElement(router, "fabric-virtual-gateway", xmlns="urn:brocade.com:mgmt:brocade-anycast-gateway")
        address_family = ET.SubElement(fabric_virtual_gateway, "address-family")
        ipv4 = ET.SubElement(address_family, "ipv4")
        enable_global = ET.SubElement(ipv4, "enable_global")
```

something like: 

``` python
    def router_fabric_virtual_gateway_address_address(self, **kwargs):
        """Example for Fabric Virtual Gateway
        """
        config = ET.Element("config")
        router = ET.SubElement(config, "router", xmlns="urn:brocade.com:mgmt:brocade-common-def")
        fabric_virtual_gateway = ET.SubElement(router, "fabric-virtual-gateway", xmlns="urn:brocade.com:mgmt:brocade-anycast-gateway")
        gateway_address = ET.SubElement(fabric_virtual_gateway, "gateway_address")
        gateway_address.text = kwargs.pop('gateway_address')

        callback = kwargs.pop('callback', self._callback)
        return callback(config)
```

(based on https://raw.githubusercontent.com/BRCDcomm/pynos/master/pynos/versions/base/yang/brocade_interface.py --> "interface_tengigabitethernet_ip_ip_config_address_addres")

As i see it, is not possible to set  Fabric-Virtual-Gateways (yet).

**Comment by samirsss** [comment]
Doesn’t look like you can do it yet, I’m working on some code to add that functionality

**Comment by chopmann** [comment]
As a workaround we implemented the feature with paramiko and normal NOS commands.

**Comment by samirsss** [comment]
That is always an option. The benefit that PyNOS will provide is validation of inputs and also guard against different Firmware versions. Will keep you posted once this gets into a build.
